/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package car4youui.HomeUI;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import Utilizador.BLL.Utilizador_BLL;
import car4youui.ModeradorUI.AddModerador;
import javaaplication1.DAL.Utilizador;


/**
 *  
 * @author utilizador
 */
public class Home extends javax.swing.JFrame {
    
    Utilizador utiToStand = null;


    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
//        ler os dados do user na frame
//        Utilizador uti = new Utilizador();
//        this.nome.setText(uti.getNome());
//        this.morada.setText(uti.getMorada());
//        this.dr.setText(uti.getDataRegisto()); 
//        this.email.setText(uti.getEmail());
//        this.tlm.setText(uti.getTelemovel().toString());
        

        
        
        List<Utilizador> listaClientes = null;
        //DefaultTableModel tmodel = new DefaultTableModel();
        //tmodel = (DefaultTableModel)listaM.getModel();
        DefaultTableModel tmodel = (DefaultTableModel)listaM.getModel();
        
        listaClientes = Utilizador_BLL.readAll();

        for(Utilizador cli : listaClientes){
            String [] linhaTabela = new String[9];
            linhaTabela[0] = cli.getIdUtilizador().toString();
            linhaTabela[1] = cli.getNome();
            linhaTabela[2] = cli.getMorada();
            linhaTabela[3] = cli.getTipo_Utilizador().toString();
            linhaTabela[4] = cli.getDistrito();
            linhaTabela[5] = cli.getCodPostal();
            linhaTabela[6] = cli.getEmail();
            linhaTabela[7] = cli.getTelemovel().toString();
            linhaTabela[8] = cli.getDataRegisto();
            
            
            tmodel.addRow(linhaTabela);
            //System.out.println(linhaTabela[0]);
        } 
    }
    
    public Home(Utilizador uti) {
        initComponents();
        
        utiToStand = uti;
        
        this.nome.setText(uti.getNome());
        this.morada.setText(uti.getMorada());
        this.email.setText(uti.getEmail());
        this.tlm.setText(uti.getTelemovel().toString());
        this.dr.setText(uti.getDataRegisto());
        
        List<Utilizador> listaClientes = null;
        //DefaultTableModel tmodel = new DefaultTableModel();
        //tmodel = (DefaultTableModel)listaM.getModel();
        DefaultTableModel tmodel = (DefaultTableModel)listaM.getModel();
        
        listaClientes = Utilizador_BLL.readAll();

        for(Utilizador cli : listaClientes){
            String [] linhaTabela = new String[9];
            linhaTabela[0] = cli.getIdUtilizador().toString();
            linhaTabela[1] = cli.getNome();
            linhaTabela[2] = cli.getMorada();
            linhaTabela[3] = cli.getTipo_Utilizador().toString();
            linhaTabela[4] = cli.getDistrito();
            linhaTabela[5] = cli.getCodPostal();
            linhaTabela[6] = cli.getEmail();
            linhaTabela[7] = cli.getTelemovel().toString();
            linhaTabela[8] = cli.getDataRegisto();
            
            
            tmodel.addRow(linhaTabela);
            //System.out.println(linhaTabela[0]);
        } 
    }

    public Home(List<Utilizador> listaObj) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        receberUser = new javax.swing.JLabel();
        listar = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaA = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        listaP = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        listaM = new javax.swing.JTable();
        novasD = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        abertoD = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        nome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        morada = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        tlm = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dr = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 0));

        receberUser.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        receberUser.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        receberUser.setText("Bem - Vindo");

        listar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        listar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                listarStateChanged(evt);
            }
        });

        listaA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(listaA);

        listar.addTab("Listar Anúncios", jScrollPane4);

        listaP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nome", "Title 2", "Title 3", "Title 4"
            }
        ));
        listaP.setCellSelectionEnabled(true);
        jScrollPane8.setViewportView(listaP);

        listar.addTab("Listar Pedidos", jScrollPane8);

        listaM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listaM.setShowVerticalLines(false);
        listaM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaMMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(listaM);

        listar.addTab("Listar Moderadores", jScrollPane9);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        novasD.addTab("Visualizar novas denúncias", jScrollPane1);

        abertoD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(abertoD);

        novasD.addTab("Visualizar denúncias em aberto", jScrollPane2);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        novasD.addTab("Visualizar histórico de denúncia", jScrollPane3);

        listar.addTab("Listar Denúncias", novasD);

        nome.setText("Nome");

        jLabel3.setText("-");

        morada.setText("Morada");

        jLabel7.setText("-");

        email.setText("Email");

        tlm.setText("Telemóvel");

        jLabel9.setText("-");

        dr.setText("Data registo");

        jLabel10.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(listar, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(receberUser))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(nome)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(morada)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(email)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(tlm)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(dr)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(receberUser)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome)
                    .addComponent(jLabel3)
                    .addComponent(morada)
                    .addComponent(jLabel7)
                    .addComponent(email)
                    .addComponent(jLabel9)
                    .addComponent(tlm)
                    .addComponent(jLabel10)
                    .addComponent(dr))
                .addGap(18, 18, 18)
                .addComponent(listar, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_listarStateChanged
        // TODO add your handling code here:
        //initComponents();

        
       

    }//GEN-LAST:event_listarStateChanged

    private void listaMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaMMouseClicked
        // TODO add your handling code here:
        
        
        int linha = this.listaM.getSelectedRow();
        int idUtilizador = Integer.parseInt((String)( (DefaultTableModel)this.listaM.getModel() ).getValueAt(linha, 0));
        
        Utilizador cli = Utilizador_BLL.read(idUtilizador);
        
        AddModerador updateCliente = new AddModerador(cli,utiToStand);
        updateCliente.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_listaMMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void maine(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable abertoD;
    private javax.swing.JLabel dr;
    private javax.swing.JLabel email;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable listaA;
    private javax.swing.JTable listaM;
    private javax.swing.JTable listaP;
    private javax.swing.JTabbedPane listar;
    private javax.swing.JLabel morada;
    private javax.swing.JLabel nome;
    private javax.swing.JTabbedPane novasD;
    private javax.swing.JLabel receberUser;
    private javax.swing.JLabel tlm;
    // End of variables declaration//GEN-END:variables
}
